data:extend({
  {
    type = "item-group",
    name = "outpost-signals",
    order = "t",
    inventory_order = "z",
    icon = "__Outpost Signals__/graphics/signals.png",
    icon_size = "32"
  },
  {
    type = "item-subgroup",
    name = "virtual-signal-cyan_blue",
    group = "outpost-signals",
    order = "1",
  },
  {
    type = "item-subgroup",
    name = "virtual-signal-dark_blue",
    group = "outpost-signals",
    order = "2",
  },
  {
    type = "item-subgroup",
    name = "virtual-signal-green",
    group = "outpost-signals",
    order = "3",
  },
  {
    type = "item-subgroup",
    name = "virtual-signal-grey",
    group = "outpost-signals",
    order = "4",
  },
  {
    type = "item-subgroup",
    name = "virtual-signal-light_blue",
    group = "outpost-signals",
    order = "5",
  },
  {
    type = "item-subgroup",
    name = "virtual-signal-lime_green",
    group = "outpost-signals",
    order = "6",
  },
  {
    type = "item-subgroup",
    name = "virtual-signal-orange",
    group = "outpost-signals",
    order = "7",
  },
  {
    type = "item-subgroup",
    name = "virtual-signal-pink",
    group = "outpost-signals",
    order = "8",
  },
  {
    type = "item-subgroup",
    name = "virtual-signal-red",
    group = "outpost-signals",
    order = "9",
  },
  {
    type = "item-subgroup",
    name = "virtual-signal-white",
    group = "outpost-signals",
    order = "10",
  },
  {
    type = "item-subgroup",
    name = "virtual-signal-yellow",
    group = "outpost-signals",
    order = "11",
  },
  {
    type = "item-subgroup",
    name = "virtual-signal-ironore",
    group = "outpost-signals",
    order = "12",
  },
  {
    type = "item-subgroup",
    name = "virtual-signal-copperore",
    group = "outpost-signals",
    order = "13",
  },
  {
    type = "item-subgroup",
    name = "virtual-signal-oil",
    group = "outpost-signals",
    order = "14",
  },
  {
    type = "item-subgroup",
    name = "virtual-signal-stoneore",
    group = "outpost-signals",
    order = "15",
  },
  {
    type = "item-subgroup",
    name = "virtual-signal-coalore",
    group = "outpost-signals",
    order = "16",
  },
  {
    type = "item-subgroup",
    name = "virtual-signal-ironplate",
    group = "outpost-signals",
    order = "17",
  },
  {
    type = "item-subgroup",
    name = "virtual-signal-copperplate",
    group = "outpost-signals",
    order = "18",
  },
  {
    type = "item-subgroup",
    name = "virtual-signal-steelplate",
    group = "outpost-signals",
    order = "19",
  },
  {
    type = "item-subgroup",
    name = "virtual-signal-greencircuit",
    group = "outpost-signals",
    order = "20",
  },
  {
    type = "item-subgroup",
    name = "virtual-signal-redcircuit",
    group = "outpost-signals",
    order = "21",
  },
  {
    type = "item-subgroup",
    name = "virtual-signal-bluecircuit",
    group = "outpost-signals",
    order = "22",
  },
  {
    type = "item-subgroup",
    name = "virtual-signal-ammo",
    group = "outpost-signals",
    order = "23",
  },
  {
    type = "item-subgroup",
    name = "virtual-signal-bot",
    group = "outpost-signals",
    order = "24",
  },
  {
    type = "item-subgroup",
    name = "virtual-signal-furnace",
    group = "outpost-signals",
    order = "25",
  },
  {
    type = "item-subgroup",
    name = "virtual-signal-modules",
    group = "outpost-signals",
    order = "26",
  },
  {
    type = "item-subgroup",
    name = "virtual-signal-repair",
    group = "outpost-signals",
    order = "27",
  },
})